swagger: "2.0"
info:
  title: "Example API"
  version: "1.0"
paths:
  /example:
    post:
      responses:
        '200':
          description: "OK"
      x-amazon-apigateway-integration:
        # uri: "${lambda_arn}"
        uri: "arn:aws:apigateway:ap-southeast-1:lambda:path/2015-03-31/functions/arn:aws:lambda:ap-southeast-1:864981712604:function:example_lambda_function/invocations"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        type: "aws_proxy"